services:
  - type: web
    name: sentintern-ai
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 1 -k uvicorn.workers.UvicornWorker src.main:app --bind 0.0.0.0:$PORT
    plan: free # Optimized for 512MB RAM
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: 30
      - key: MODEL_PATH
        value: ./models/finetuned_distilbert
      - key: PYTHON_VERSION
        value: 3.10.12
